### ISSUE TITLE
[RFE] Filter pull requests by repository

### ISSUE THREAD

**Issue by jwhonce** [clstb/logsync#1]
I've been using your plugin to help me find and manage pull requests. I found a number of my PRs that have languished for some time. They are against archived repositories so I cannot `close` them. It would clean up my `github/pull-requests` page if those repositories could be skipped/filtered from the results. A list of blacklisted repositories would be sufficient for my needs.

Thank you for your time and efforts!

**Comment by clstb** [comment]
Implemented in https://github.com/clstb/logsync/commit/f45551cf71e13583287c327f91315acf102f60c5, sorry it took so long.

**Comment by jwhonce** [comment]
@clstb Thank you, works as expected.
